---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  splunk-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
